baseURL = "http://example.org/"
languageCode = "en-us"
title = "Changhyun An"
theme = "just-a-card"

[author]
  name = "Changhyun An âœ¨"
  title = "Backend Software Engineer ğŸ‘¨â€ğŸ’»"
  location = "Seoul, Korea ğŸ‡°ğŸ‡·"
  company = "Unemployed"
  companyUrl = "#"
  intro = """
    Hi! ğŸ‘‹
    I'm a software engineer with fundamental knowledge and experience of building webğŸ•¸ applications and REST APIs utilizing cloud services.
    Also, a diligent and passionate learner with fine learning curve who craves for continuous improvement ğŸƒğŸ“ˆ.
    I like to work with Python and NodeJS. 
    I dream of building something beneficial to humanity ğŸš€!
  """
  profile_image = "images/profile.jpeg"

[params]
  primary_color = "#F2F4EF"
  secondary_color = "#295651"
  google_font = "Overpass"
  [[params.links]]
    icon = "link"
    name = "E-mail"
    url = "mailto:88soldieron@gmail.com"
  [[params.links]]
    icon = "github"
    name = "Github"
    url = "https://github.com/achooan"
  [[params.links]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/changhyun-an-240b71116/"
  [[params.links]]
    icon = "file-text"
    name = "Hire me!"
    url = "https://bit.ly/2UTe8eX"